" basic set up {{{
autocmd! bufwritepost $MYVIMRC source $MYVIMRC " auto reread .vimrc file after save {{{

set nocompatible
syntax on		" syntax for programming on
set number 		" set up line numbers
set showcmd 		" show comands in-action in the coman line
set lines=100 columns=100 " window 100x100
set laststatus=2	" always see last command
set ruler
set autoread		" reread file

set t_Co=256
colorscheme monokai " colorshema like Sublime Text
" file type detection
filetype plugin indent on
" Make backspace usefull
set backspace=indent,eol,start
fixdel " Fix my del please :)

if has('gui')
	set guioptions-=e " gui Tabs - off
	set guioptions-=T " gui icons - off
endif
" Add mouse
if has('mouse')
  set mouse=a
endif
if has('win32')
   set guifont=Lucida_Console:h10:cRUSSIAN::
endif
" }}}

" install plug-ins {{{
" I use vim-plug --> https://github.com/junegunn/vim-plug
call plug#begin('~/.vim/plugged')
	Plug 'ctrlpvim/ctrlp.vim'
	Plug 'bling/vim-airline'
	Plug 'vim-airline/vim-airline-themes'
call plug#end()

" hot kays set-up {{{
" <C-s> for save file 
nmap <C-s> :w<cr> 
vmap <C-s> <esc>:w<cr>i
imap <C-s> <esc>:w<cr>i

" }}}

" Plug-in setup {{{
" vim-anderline-themes setup
let g:airline_theme ='bubblegum'
" }}}
